### ISSUE TITLE
TypeError: require(...) is not a function

### ISSUE THREAD

**Issue by luane-aquino** [scottdomes/notable-node-api-tutorial#1]
I am following the tutorial in the create part, and I am getting this error, I searched but couldn't find a solution.  

Here is the code:

```
const MongoClient = require('mongodb').MongoClient
const express = require('express')
const app = express()
const port = 8000

require('./app/routes')(app, {})

app.listen(port, () => { console.log('We are live on ' + port); })
```
And the error message:

[nodemon] restarting due to changes...
[nodemon] starting `node server.js`
/home/luane/Learning/node.js/creating-api-freecodecamp/server.js:6
require('./app/routes')(app, {})
                       ^

TypeError: require(...) is not a function
    at Object.<anonymous> (/home/luane/Learning/node.js/creating-api-freecodecamp/server.js:6:24)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
[nodemon] app crashed - waiting for file changes before starting...

**Comment by luane-aquino** [comment]
I think I was a problem with nodemon. I tested running the file without nodemon and it worked. I then restarted vscode IDE and this time tried using nodemon again, and it worked.
